event/core/base/urls.py
from django.urls import path 


from .views import (home_page, event_page, registration_confirmation,
                        profile_page, account_page, project_submission,
                        update_submission,)

# namespace
app_name = 'event'

urlpatterns = [
    path('', home_page, name='index'),
    path('user/<str:pk>/', profile_page, name='profile'),
    path('account/', account_page, name='account'),
    path('event/<str:event_id>/', event_page, name='event'),
    path('registration-confirmation/<str:event_id>/', registration_confirmation, name='confirmation'),
    path('project-submission/<str:pk>/', project_submission, name='submission'),
    path('update-submission/<str:pk>/', update_submission, name='update-submission'),

]

event/event/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.base.urls')),
    path('admin/', admin.site.urls),
]

event/core/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class CustomUser(AbstractUser):
    email = models.EmailField(verbose_name='User Email', max_length=20, unique=True,)
    bio = models.TextField(null=True, blank=True)
    avatar = models.ImageField(default='avatar.jpg')      
    hackthon_participant = models.BooleanField(default=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    def __str__(self):
        return self.username

event/core/base/models.py
from django.db import models
from PIL import Image 
from django.utils import timezone
from django.conf import settings

from core.accounts.models import CustomUser

class Event(models.Model):
    name = models.CharField(max_length=200)
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='events')
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # auto_add_now = makes field efitable on admin field
    # auto_now =  inherit editable=False

    # def save(self, *args, **kwargs):
    #     ''' On save, update timestamp'''
    #     if not self.id:
    #         self.created_at = timezone.now()
    #     self.updated_at = timezone.now()

    #     return super(CustomUser, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Submission(models.Model):
    participant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='submissions')
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, null=True)
    detail = models.TextField(null=True, blank=True)


    def __str__(self):
        return f" {str(self.event)} {str(self.participant)}"
        

event/core/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = '__all__'

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = '__all__' 

event/core/base/forms.py
from django.forms import ModelForm

from .models import Submission

class ProjectSubmissionForm(ModelForm):

    class Meta:
        model = Submission
        fields = ['detail']

event/core/accounts/views.py
from django.shortcuts import render

# Create your views here.

event/core/base/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect

from django.contrib import messages

from .models import Event, Submission

from core.accounts.models import CustomUser
from .forms import ProjectSubmissionForm

def home_page(request):
    users = CustomUser.objects.filter(hackthon_participant=True)
    events = Event.objects.all()

    context = {
        'events': events,
        'users': users,
        'title': 'Home',
    }
    return render(request, 'home.html', context)


def profile_page(request, pk):
    user = get_object_or_404(CustomUser, id=pk)
    context = {
        'title': "Profile Section",
        "user": user,
    }

    return render(request, 'profile.html', context)


def account_page(request):
    user = request.user
    context = {
        'user': user,
        'title': "Account Page"
    }
    return render(request, 'account.html', context)


def event_page(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    # get events user is registered for -> move to model method, if user registerd, disable reg button
    registered = request.user.events.filter(id=event.id).exists()
    submitted = Submission.objects.filter(participant=request.user, event=event).exists()
    # print("You're registerd for:", registered)
    context = {
        'event': event, 
        'registered':registered,
        'submitted':submitted,
        'title': 'Event Detail',
    }
    return render(request, 'event.html', context)

def registration_confirmation(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    
    if request.method == 'POST':
        # event = Event.objects.get(id=request.POST.get('event'))
        # print(event) 
        print(request.user)
        event.participants.add(request.user)
        messages.success(request, 'Your event registration has been confirmed')
        return redirect('event:event', event_id=event.id)
    # else:
    #     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    context = {
        'event': event,
    }
    return render(request, 'event_confirmation.html', context)
    

def project_submission(request, pk):
    event = get_object_or_404(Event, id=pk)
    if request.method == 'GET':
        form = ProjectSubmissionForm()

    if request.method == 'POST':
        form = ProjectSubmissionForm(request.POST or None)
        if form.is_valid():
            form_payload = form.save(commit=False)
            form_payload.participant = request.user
            form_payload.event = event
            form_payload.save()
        
        messages.success(request, "Project has been submitted successfully.")
        return redirect('event:profile', pk=event.id)

    context = {
        'event': event,
        'title': "Submit Project",
        'form': form,
    }
    return render(request, 'submit_form.html', context)


def update_submission(request, pk):
    submission = get_object_or_404(Submission, pk=id)
    event = get_object_or_404(Event, id=pk)
    form = ProjectSubmissionForm(instance=submission)
    context = {
        'submission': submission,
        'form': form,
    }

    return render(request, 'update_submission.html', context)

event/templates/account.html
{% extends 'base.html' %}


{% block content %}
    <h1>My Account</h1>
    <div>
        <h3>My Events</h3>
        {% for event in user.events.all %}
            <a href="{% url 'event:event' event.id %}">{{ event.name }}</a>
        {% endfor %}
            
    </div>

    <div>
        <h3>My Submissions</h3>
        {% for sub in user.submissions.all %}
            <a href="{% url 'event:event' event.id %}">{{ sub.event.name }}</a>
        {% endfor %}
            
    </div>
{% endblock content %}
    

event/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstraop -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Home - {{ title }}</title>
    {% endif %}
        
</head>
<body>
    <div class="container">
        {% include 'navbar.html' %}

        
        {% for message in messages %}
            
            {% if message %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true" >&times;</span>
                    </button>
                </div>
            {% endif %}
                
        {% endfor %}
            
        {% block content %}
            
        {% endblock content %}
            
    </div>


    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    {% block script %}
        
    {% endblock script %}
        
</body>
</html>

event/templates/event.html
{% extends 'base.html' %}


{% block content %}
    <h2>{{ event.name }}</h2>
    <p>{{ event.description }}</p>
    
    {% if registered %} 
    <div class="alert alert-info">
        <strong>You've already Registered for this event.</strong>
        <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% else %}
        <a href="{% url 'event:confirmation' event.id %}" class="disabled">Register</a>
    {% endif %}
    
    {% if submitted %}
    <div class="alert alert-info" role="alert">
        <strong>You've already submitted for this project.</strong>
        <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

    </div>
    {% else %}
        <a href="{% url 'event:submission' event.id %}" class="submitted">Submit Project</a>   
    {% endif %}
        

    <div>
        <h3>Event Participants</h3>
        <div>
            
            {% for user in event.participants.all %}
                <div>
                    <strong>{{ user.first_name }}</strong>
                </div>
            {% endfor %}
                
        </div>
    </div>
{% endblock content %}


{% block script %}
    <script> 
        // const disabled = document.querySelector('.disabled')
        // disabled.href="javascript:alert('You\\'ve already registered for this event.')";

        // let submitted = document.querySelector('.submitted')
        // submitted.href="javascript:alert('You\\'ve already made a submission on this project.')";
    </script>
{% endblock script %}

    

event/templates/event_confirmation.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post">{% csrf_token %}
        <a href="{% url 'event:event' event.id %}">Go Back</a>

        <input type="hidden" name="event" value="{{ event.id }}">
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}
    

event/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <h1>Home Page</h1>

    <section>
        <h3>Events</h3>
        <div id="event-lists">
            
            {% for event in events %}
                <a href="{% url 'event:event' event.id %}">
                    <div>
                        {{ event.name }}
                    </div>
                </a>
            {% endfor %}
                
        </div>
    </section>

    <section>
        <h3>Users</h3>
        
        {% for user in users %}
            <a href="{% url 'event:profile' user.id %}">
                <div>
                    {{ user.first_name }}
                </div>
            </a>
        {% endfor %}
            
    </section>
{% endblock content %}
    

event/templates/navbar.html
<nav>
    <a href="{% url 'event:index' %}">Home</a>

    
    {% if request.user.is_authenticated %}
        <a href="{% url 'event:account' %}">Profile</a>
        <a href="#">Log Out</a>
    {% else %}
        <a href="#">Login</a>
    {% endif %}
        
</nav>

event/templates/profile.html
{% extends 'base.html' %}


{% block content %}
    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
{% endblock content %}
    

event/templates/submit_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h4>Project Submission for - {{ event.name }}</h4>

    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
    
            <input type="submit" class="btn btn-success" value="Submit">
        </form>
    </div>
    

{% endblock content %}
    

event/templates/update_submission.html
extends 'base.html'
{% load crispy_forms_tags %}

{% block content %}
    <h1>Update Submission</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
    </form>
{% endblock content %}